//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witcher3StringEditor.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Data 的本地化字符串。
        /// </summary>
        internal static string AddBtnLabel {
            get {
                return ResourceManager.GetString("AddBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Supported Format 的本地化字符串。
        /// </summary>
        internal static string AllSupportedFormat {
            get {
                return ResourceManager.GetString("AllSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Witcher 3 String Editor 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        internal static string BackupBtnLabel {
            get {
                return ResourceManager.GetString("BackupBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Operation Will Delete The File And Cannot Be Undone 的本地化字符串。
        /// </summary>
        internal static string BackupDeleteMessage {
            get {
                return ResourceManager.GetString("BackupDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        internal static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Path 的本地化字符串。
        /// </summary>
        internal static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Operation Will Overwrite The File And Cannot Be Undone 的本地化字符串。
        /// </summary>
        internal static string BackupRestoreMessage {
            get {
                return ResourceManager.GetString("BackupRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Time 的本地化字符串。
        /// </summary>
        internal static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build Time 的本地化字符串。
        /// </summary>
        internal static string BuildTime {
            get {
                return ResourceManager.GetString("BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelBtnTxt {
            get {
                return ResourceManager.GetString("CancelBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseBtnTxt {
            get {
                return ResourceManager.GetString("CloseBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Data 的本地化字符串。
        /// </summary>
        internal static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteBtnTxt {
            get {
                return ResourceManager.GetString("DeleteBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You Are Deleting These Record(s): 的本地化字符串。
        /// </summary>
        internal static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Data 的本地化字符串。
        /// </summary>
        internal static string EditBtnLabel {
            get {
                return ResourceManager.GetString("EditBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select witcher3.exe 的本地化字符串。
        /// </summary>
        internal static string GameExePath {
            get {
                return ResourceManager.GetString("GameExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash 的本地化字符串。
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID Space 的本地化字符串。
        /// </summary>
        internal static string IDSpace {
            get {
                return ResourceManager.GetString("IDSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore ID Space Check     的本地化字符串。
        /// </summary>
        internal static string IgnoreIDSpaceCheck {
            get {
                return ResourceManager.GetString("IgnoreIDSpaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string LogBtnLabel {
            get {
                return ResourceManager.GetString("LogBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string LogDialogTitle {
            get {
                return ResourceManager.GetString("LogDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Level 的本地化字符串。
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Message 的本地化字符串。
        /// </summary>
        internal static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Time 的本地化字符串。
        /// </summary>
        internal static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        internal static string OpenFileBtnLabel {
            get {
                return ResourceManager.GetString("OpenFileBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orgin Path 的本地化字符串。
        /// </summary>
        internal static string OrginPath {
            get {
                return ResourceManager.GetString("OrginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS 的本地化字符串。
        /// </summary>
        internal static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Game 的本地化字符串。
        /// </summary>
        internal static string PlayBtnLabel {
            get {
                return ResourceManager.GetString("PlayBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You Have Not Completed The Initialization. Click Yes to Exit,Otherwise Click No To Continue With The Initialization. 的本地化字符串。
        /// </summary>
        internal static string PleaseCheckSettings {
            get {
                return ResourceManager.GetString("PleaseCheckSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Filetype 的本地化字符串。
        /// </summary>
        internal static string PreferredFiletype {
            get {
                return ResourceManager.GetString("PreferredFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Language 的本地化字符串。
        /// </summary>
        internal static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        internal static string RestoreBtnTxt {
            get {
                return ResourceManager.GetString("RestoreBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime 的本地化字符串。
        /// </summary>
        internal static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveBtnTxt {
            get {
                return ResourceManager.GetString("SaveBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Failure 的本地化字符串。
        /// </summary>
        internal static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Result 的本地化字符串。
        /// </summary>
        internal static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Success 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select witcher3.exe 的本地化字符串。
        /// </summary>
        internal static string SelectGameExe {
            get {
                return ResourceManager.GetString("SelectGameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select w3strings.exe 的本地化字符串。
        /// </summary>
        internal static string SelectW3Strings {
            get {
                return ResourceManager.GetString("SelectW3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsBtnLabel {
            get {
                return ResourceManager.GetString("SettingsBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string SubmitBtnTxt {
            get {
                return ResourceManager.GetString("SubmitBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Filetype 的本地化字符串。
        /// </summary>
        internal static string TargetFiletype {
            get {
                return ResourceManager.GetString("TargetFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Language 的本地化字符串。
        /// </summary>
        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File 的本地化字符串。
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select w3strings.exe 的本地化字符串。
        /// </summary>
        internal static string W3StringsPath {
            get {
                return ResourceManager.GetString("W3StringsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Witcher3 Strings File 的本地化字符串。
        /// </summary>
        internal static string Witcher3StringsFile {
            get {
                return ResourceManager.GetString("Witcher3StringsFile", resourceCulture);
            }
        }
    }
}
