//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witcher3StringEditor.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data.
        /// </summary>
        internal static string AddBtnLabel {
            get {
                return ResourceManager.GetString("AddBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Format.
        /// </summary>
        internal static string AllSupportedFormat {
            get {
                return ResourceManager.GetString("AllSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witcher 3 String Editor.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupBtnLabel {
            get {
                return ResourceManager.GetString("BackupBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Operation Will Delete The File And Cannot Be Undone.
        /// </summary>
        internal static string BackupDeleteMessage {
            get {
                return ResourceManager.GetString("BackupDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Path.
        /// </summary>
        internal static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Operation Will Overwrite The File And Cannot Be Undone.
        /// </summary>
        internal static string BackupRestoreMessage {
            get {
                return ResourceManager.GetString("BackupRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Time.
        /// </summary>
        internal static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Time.
        /// </summary>
        internal static string BuildTime {
            get {
                return ResourceManager.GetString("BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtnTxt {
            get {
                return ResourceManager.GetString("CancelBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseBtnTxt {
            get {
                return ResourceManager.GetString("CloseBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data.
        /// </summary>
        internal static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtnTxt {
            get {
                return ResourceManager.GetString("DeleteBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Deleting These Record(s):.
        /// </summary>
        internal static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data.
        /// </summary>
        internal static string EditBtnLabel {
            get {
                return ResourceManager.GetString("EditBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select witcher3.exe.
        /// </summary>
        internal static string GameExePath {
            get {
                return ResourceManager.GetString("GameExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Space.
        /// </summary>
        internal static string IDSpace {
            get {
                return ResourceManager.GetString("IDSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore ID Space Check    .
        /// </summary>
        internal static string IgnoreIDSpaceCheck {
            get {
                return ResourceManager.GetString("IgnoreIDSpaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string IsOff {
            get {
                return ResourceManager.GetString("IsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string IsOn {
            get {
                return ResourceManager.GetString("IsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogBtnLabel {
            get {
                return ResourceManager.GetString("LogBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogDialogTitle {
            get {
                return ResourceManager.GetString("LogDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        internal static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        internal static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string OpenFileBtnLabel {
            get {
                return ResourceManager.GetString("OpenFileBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Working Folder.
        /// </summary>
        internal static string OpenWorkingFolderBtnLabel {
            get {
                return ResourceManager.GetString("OpenWorkingFolderBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgin Path.
        /// </summary>
        internal static string OrginPath {
            get {
                return ResourceManager.GetString("OrginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        internal static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Game.
        /// </summary>
        internal static string PlayBtnLabel {
            get {
                return ResourceManager.GetString("PlayBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Not Completed The Initialization. Click Yes to Exit,Otherwise Click No To Continue With The Initialization..
        /// </summary>
        internal static string PleaseCheckSettings {
            get {
                return ResourceManager.GetString("PleaseCheckSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Filetype.
        /// </summary>
        internal static string PreferredFiletype {
            get {
                return ResourceManager.GetString("PreferredFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        internal static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string RestoreBtnTxt {
            get {
                return ResourceManager.GetString("RestoreBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        internal static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtnTxt {
            get {
                return ResourceManager.GetString("SaveBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failure.
        /// </summary>
        internal static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Result.
        /// </summary>
        internal static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select witcher3.exe.
        /// </summary>
        internal static string SelectGameExe {
            get {
                return ResourceManager.GetString("SelectGameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select w3strings.exe.
        /// </summary>
        internal static string SelectW3Strings {
            get {
                return ResourceManager.GetString("SelectW3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsBtnLabel {
            get {
                return ResourceManager.GetString("SettingsBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitBtnTxt {
            get {
                return ResourceManager.GetString("SubmitBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Filetype.
        /// </summary>
        internal static string TargetFiletype {
            get {
                return ResourceManager.GetString("TargetFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File.
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select w3strings.exe.
        /// </summary>
        internal static string W3StringsPath {
            get {
                return ResourceManager.GetString("W3StringsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witcher3 Strings File.
        /// </summary>
        internal static string Witcher3StringsFile {
            get {
                return ResourceManager.GetString("Witcher3StringsFile", resourceCulture);
            }
        }
    }
}
