//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witcher3StringEditor.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string AboutBtnLabel {
            get {
                return ResourceManager.GetString("AboutBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Data 的本地化字符串。
        /// </summary>
        internal static string AddBtnLabel {
            get {
                return ResourceManager.GetString("AddBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string AppExitCaption {
            get {
                return ResourceManager.GetString("AppExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit? Any unsaved data will be lost. 的本地化字符串。
        /// </summary>
        internal static string AppExitMessage {
            get {
                return ResourceManager.GetString("AppExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Witcher 3 String Editor 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        internal static string BackupBtnLabel {
            get {
                return ResourceManager.GetString("BackupBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Data 的本地化字符串。
        /// </summary>
        internal static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag and Drop A Single File Here To Open 的本地化字符串。
        /// </summary>
        internal static string DropHereTxt {
            get {
                return ResourceManager.GetString("DropHereTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Data 的本地化字符串。
        /// </summary>
        internal static string EditBtnLabel {
            get {
                return ResourceManager.GetString("EditBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel Worksheets 的本地化字符串。
        /// </summary>
        internal static string FileFormatExcelWorkSheets {
            get {
                return ResourceManager.GetString("FileFormatExcelWorkSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Supported Format 的本地化字符串。
        /// </summary>
        internal static string FileFormatSupported {
            get {
                return ResourceManager.GetString("FileFormatSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File 的本地化字符串。
        /// </summary>
        internal static string FileFormatTextFile {
            get {
                return ResourceManager.GetString("FileFormatTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Witcher3 Strings File 的本地化字符串。
        /// </summary>
        internal static string FileFormatWitcher3StringsFile {
            get {
                return ResourceManager.GetString("FileFormatWitcher3StringsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        internal static string FileOpenedCaption {
            get {
                return ResourceManager.GetString("FileOpenedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening this file will result in the loss of any unsaved data. Do you want to continue? 的本地化字符串。
        /// </summary>
        internal static string FileOpenedMessage {
            get {
                return ResourceManager.GetString("FileOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened File Not Found 的本地化字符串。
        /// </summary>
        internal static string FileOpenedNoFoundCaption {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The opened file does not exist. Do you want to delete the associated record? 的本地化字符串。
        /// </summary>
        internal static string FileOpenedNoFoundMessage {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First-Run Setup Prompt 的本地化字符串。
        /// </summary>
        internal static string FristRunCaption {
            get {
                return ResourceManager.GetString("FristRunCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Required) When running for the first time, please set the encoder path first.
        ///(Optional) Set the game executable path to launch the game directly in the software. 的本地化字符串。
        /// </summary>
        internal static string FristRunMessage {
            get {
                return ResourceManager.GetString("FristRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string LogBtnLabel {
            get {
                return ResourceManager.GetString("LogBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software is already running 的本地化字符串。
        /// </summary>
        internal static string MultipleInstanceCaption {
            get {
                return ResourceManager.GetString("MultipleInstanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple instances may cause data to be overwritten incorrectly. Only single instance is supported. Click the button to wake up the open window. 的本地化字符串。
        /// </summary>
        internal static string MultipleInstanceMessage {
            get {
                return ResourceManager.GetString("MultipleInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        internal static string OpenFileBtnLabel {
            get {
                return ResourceManager.GetString("OpenFileBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Working Folder 的本地化字符串。
        /// </summary>
        internal static string OpenWorkingFolderBtnLabel {
            get {
                return ResourceManager.GetString("OpenWorkingFolderBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Game 的本地化字符串。
        /// </summary>
        internal static string PlayBtnLabel {
            get {
                return ResourceManager.GetString("PlayBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 的本地化字符串。
        /// </summary>
        internal static string RecentBtnLabel {
            get {
                return ResourceManager.GetString("RecentBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime 的本地化字符串。
        /// </summary>
        internal static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsBtnLabel {
            get {
                return ResourceManager.GetString("SettingsBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        internal static string TranslateBtnLabel {
            get {
                return ResourceManager.GetString("TranslateBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Available 的本地化字符串。
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string UpdateBtnContent {
            get {
                return ResourceManager.GetString("UpdateBtnContent", resourceCulture);
            }
        }
    }
}
