//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Locales {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Witcher3StringEditor.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        public static string OpenFileBtnLabel {
            get {
                return ResourceManager.GetString("OpenFileBtnLabel", resourceCulture);
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        public static string AddBtnLabel {
            get {
                return ResourceManager.GetString("AddBtnLabel", resourceCulture);
            }
        }
        
        public static string EditBtnLabel {
            get {
                return ResourceManager.GetString("EditBtnLabel", resourceCulture);
            }
        }
        
        public static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        public static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        public static string BackupBtnLabel {
            get {
                return ResourceManager.GetString("BackupBtnLabel", resourceCulture);
            }
        }
        
        public static string LogBtnLabel {
            get {
                return ResourceManager.GetString("LogBtnLabel", resourceCulture);
            }
        }
        
        public static string SettingsBtnLabel {
            get {
                return ResourceManager.GetString("SettingsBtnLabel", resourceCulture);
            }
        }
        
        public static string PlayBtnLabel {
            get {
                return ResourceManager.GetString("PlayBtnLabel", resourceCulture);
            }
        }
        
        public static string TranslateBtnLabel {
            get {
                return ResourceManager.GetString("TranslateBtnLabel", resourceCulture);
            }
        }
        
        public static string OpenWorkingFolderBtnLabel {
            get {
                return ResourceManager.GetString("OpenWorkingFolderBtnLabel", resourceCulture);
            }
        }
        
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        public static string CheckUpdatesBtnLabel {
            get {
                return ResourceManager.GetString("CheckUpdatesBtnLabel", resourceCulture);
            }
        }
        
        public static string RecentBtnLabel {
            get {
                return ResourceManager.GetString("RecentBtnLabel", resourceCulture);
            }
        }
        
        public static string AboutBtnLabel {
            get {
                return ResourceManager.GetString("AboutBtnLabel", resourceCulture);
            }
        }
        
        public static string FileFormatSupported {
            get {
                return ResourceManager.GetString("FileFormatSupported", resourceCulture);
            }
        }
        
        public static string FileFormatTextFile {
            get {
                return ResourceManager.GetString("FileFormatTextFile", resourceCulture);
            }
        }
        
        public static string FileFormatTerminology {
            get {
                return ResourceManager.GetString("FileFormatTerminology", resourceCulture);
            }
        }
        
        public static string FileFormatStyleGuide {
            get {
                return ResourceManager.GetString("FileFormatStyleGuide", resourceCulture);
            }
        }
        
        public static string FileFormatWitcher3StringsFile {
            get {
                return ResourceManager.GetString("FileFormatWitcher3StringsFile", resourceCulture);
            }
        }
        
        public static string AppExitMessage {
            get {
                return ResourceManager.GetString("AppExitMessage", resourceCulture);
            }
        }
        
        public static string AppExitCaption {
            get {
                return ResourceManager.GetString("AppExitCaption", resourceCulture);
            }
        }
        
        public static string FileOpenedNoFoundMessage {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundMessage", resourceCulture);
            }
        }
        
        public static string ReOpenFileMessage {
            get {
                return ResourceManager.GetString("ReOpenFileMessage", resourceCulture);
            }
        }
        
        public static string ReOpenFileCaption {
            get {
                return ResourceManager.GetString("ReOpenFileCaption", resourceCulture);
            }
        }
        
        public static string FileOpenedNoFoundCaption {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundCaption", resourceCulture);
            }
        }
        
        public static string UpdateBtnContent {
            get {
                return ResourceManager.GetString("UpdateBtnContent", resourceCulture);
            }
        }
        
        public static string DropHereTxt {
            get {
                return ResourceManager.GetString("DropHereTxt", resourceCulture);
            }
        }
        
        public static string FileFormatExcelWorkbook {
            get {
                return ResourceManager.GetString("FileFormatExcelWorkbook", resourceCulture);
            }
        }
        
        public static string FristRunMessage {
            get {
                return ResourceManager.GetString("FristRunMessage", resourceCulture);
            }
        }
        
        public static string FristRunCaption {
            get {
                return ResourceManager.GetString("FristRunCaption", resourceCulture);
            }
        }
        
        public static string MultipleInstanceMessage {
            get {
                return ResourceManager.GetString("MultipleInstanceMessage", resourceCulture);
            }
        }
        
        public static string MultipleInstanceCaption {
            get {
                return ResourceManager.GetString("MultipleInstanceCaption", resourceCulture);
            }
        }
        
        public static string BackupRestoreMessage {
            get {
                return ResourceManager.GetString("BackupRestoreMessage", resourceCulture);
            }
        }
        
        public static string BackupDeleteMessage {
            get {
                return ResourceManager.GetString("BackupDeleteMessage", resourceCulture);
            }
        }
        
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        public static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        public static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        public static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        public static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        public static string SelectW3Strings {
            get {
                return ResourceManager.GetString("SelectW3Strings", resourceCulture);
            }
        }
        
        public static string SelectGameExe {
            get {
                return ResourceManager.GetString("SelectGameExe", resourceCulture);
            }
        }
        
        public static string SelectTerminologyFile {
            get {
                return ResourceManager.GetString("SelectTerminologyFile", resourceCulture);
            }
        }
        
        public static string SelectStyleGuideFile {
            get {
                return ResourceManager.GetString("SelectStyleGuideFile", resourceCulture);
            }
        }
        
        public static string SubmitBtnContent {
            get {
                return ResourceManager.GetString("SubmitBtnContent", resourceCulture);
            }
        }
        
        public static string CancelBtnContent {
            get {
                return ResourceManager.GetString("CancelBtnContent", resourceCulture);
            }
        }
        
        public static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        public static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        public static string DeleteBtnContent {
            get {
                return ResourceManager.GetString("DeleteBtnContent", resourceCulture);
            }
        }
        
        public static string TranslateDialogTitle {
            get {
                return ResourceManager.GetString("TranslateDialogTitle", resourceCulture);
            }
        }
        
        public static string PreviousBtnContent {
            get {
                return ResourceManager.GetString("PreviousBtnContent", resourceCulture);
            }
        }
        
        public static string NextBtnContent {
            get {
                return ResourceManager.GetString("NextBtnContent", resourceCulture);
            }
        }
        
        public static string TranslateBtnContent {
            get {
                return ResourceManager.GetString("TranslateBtnContent", resourceCulture);
            }
        }
        
        public static string SaveBtnContent {
            get {
                return ResourceManager.GetString("SaveBtnContent", resourceCulture);
            }
        }
        
        public static string SrcTxt {
            get {
                return ResourceManager.GetString("SrcTxt", resourceCulture);
            }
        }
        
        public static string TranslatedTxt {
            get {
                return ResourceManager.GetString("TranslatedTxt", resourceCulture);
            }
        }
        
        public static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        public static string TargetFiletype {
            get {
                return ResourceManager.GetString("TargetFiletype", resourceCulture);
            }
        }
        
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        public static string IgnoreIDSpaceCheck {
            get {
                return ResourceManager.GetString("IgnoreIDSpaceCheck", resourceCulture);
            }
        }
        
        public static string IDSpace {
            get {
                return ResourceManager.GetString("IDSpace", resourceCulture);
            }
        }
        
        public static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        public static string OriginPath {
            get {
                return ResourceManager.GetString("OriginPath", resourceCulture);
            }
        }
        
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        public static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        public static string RestoreBtnContent {
            get {
                return ResourceManager.GetString("RestoreBtnContent", resourceCulture);
            }
        }
        
        public static string CloseBtnContent {
            get {
                return ResourceManager.GetString("CloseBtnContent", resourceCulture);
            }
        }
        
        public static string LogDialogTitle {
            get {
                return ResourceManager.GetString("LogDialogTitle", resourceCulture);
            }
        }
        
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        public static string SettingsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialogTitle", resourceCulture);
            }
        }
        
        public static string W3StringsPath {
            get {
                return ResourceManager.GetString("W3StringsPath", resourceCulture);
            }
        }
        
        public static string GameExePath {
            get {
                return ResourceManager.GetString("GameExePath", resourceCulture);
            }
        }
        
        public static string PreferredFileType {
            get {
                return ResourceManager.GetString("PreferredFileType", resourceCulture);
            }
        }
        
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        public static string IsOn {
            get {
                return ResourceManager.GetString("IsOn", resourceCulture);
            }
        }
        
        public static string IsOff {
            get {
                return ResourceManager.GetString("IsOff", resourceCulture);
            }
        }
        
        public static string IdSpaceToolTip {
            get {
                return ResourceManager.GetString("IdSpaceToolTip", resourceCulture);
            }
        }
        
        public static string RecentDialogTitle {
            get {
                return ResourceManager.GetString("RecentDialogTitle", resourceCulture);
            }
        }
        
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        public static string OpenedTime {
            get {
                return ResourceManager.GetString("OpenedTime", resourceCulture);
            }
        }
        
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        public static string RecordDeletingMessgae {
            get {
                return ResourceManager.GetString("RecordDeletingMessgae", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        public static string EndIndex {
            get {
                return ResourceManager.GetString("EndIndex", resourceCulture);
            }
        }
        
        public static string BatchTranslateDialogTitle {
            get {
                return ResourceManager.GetString("BatchTranslateDialogTitle", resourceCulture);
            }
        }
        
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        public static string TranslatedTextInvalidMessage {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidMessage", resourceCulture);
            }
        }
        
        public static string BackupFileNoFoundMessage {
            get {
                return ResourceManager.GetString("BackupFileNoFoundMessage", resourceCulture);
            }
        }
        
        public static string BackupFileNoFoundCaption {
            get {
                return ResourceManager.GetString("BackupFileNoFoundCaption", resourceCulture);
            }
        }
        
        public static string BackupDeleteCaption {
            get {
                return ResourceManager.GetString("BackupDeleteCaption", resourceCulture);
            }
        }
        
        public static string BackupRestoreCaption {
            get {
                return ResourceManager.GetString("BackupRestoreCaption", resourceCulture);
            }
        }
        
        public static string TranslatedTextInvalidCaption {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidCaption", resourceCulture);
            }
        }
        
        public static string TranslateErrorCaption {
            get {
                return ResourceManager.GetString("TranslateErrorCaption", resourceCulture);
            }
        }
        
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        public static string TranslatedTextNoSavedMessage {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedMessage", resourceCulture);
            }
        }
        
        public static string TranslatedTextNoSavedCaption {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedCaption", resourceCulture);
            }
        }
        
        public static string OperationResultCaption {
            get {
                return ResourceManager.GetString("OperationResultCaption", resourceCulture);
            }
        }
        
        public static string OperationFailureMessage {
            get {
                return ResourceManager.GetString("OperationFailureMessage", resourceCulture);
            }
        }
        
        public static string RecordDeletingCaption {
            get {
                return ResourceManager.GetString("RecordDeletingCaption", resourceCulture);
            }
        }
        
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        public static string AppBuildTime {
            get {
                return ResourceManager.GetString("AppBuildTime", resourceCulture);
            }
        }
        
        public static string EncoderSettingCardHeader {
            get {
                return ResourceManager.GetString("EncoderSettingCardHeader", resourceCulture);
            }
        }
        
        public static string GameSettingCardHeader {
            get {
                return ResourceManager.GetString("GameSettingCardHeader", resourceCulture);
            }
        }
        
        public static string GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("GeneralSettingsHeader", resourceCulture);
            }
        }
        
        public static string TranslatorTranslatingMessage {
            get {
                return ResourceManager.GetString("TranslatorTranslatingMessage", resourceCulture);
            }
        }
        
        public static string TranslatorTranslatingCaption {
            get {
                return ResourceManager.GetString("TranslatorTranslatingCaption", resourceCulture);
            }
        }
        
        public static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        public static string TranslationModeSwitchCaption {
            get {
                return ResourceManager.GetString("TranslationModeSwitchCaption", resourceCulture);
            }
        }
        
        public static string TranslationModeSwitchMessage {
            get {
                return ResourceManager.GetString("TranslationModeSwitchMessage", resourceCulture);
            }
        }
        
        public static string TranslationNotEmptyMessage {
            get {
                return ResourceManager.GetString("TranslationNotEmptyMessage", resourceCulture);
            }
        }
        
        public static string TranslationNotEmptyCaption {
            get {
                return ResourceManager.GetString("TranslationNotEmptyCaption", resourceCulture);
            }
        }
        
        public static string TranslatorSelection {
            get {
                return ResourceManager.GetString("TranslatorSelection", resourceCulture);
            }
        }
        
        public static string UserInterfaceSettingsHeader {
            get {
                return ResourceManager.GetString("UserInterfaceSettingsHeader", resourceCulture);
            }
        }
        
        public static string LanguageHelpText {
            get {
                return ResourceManager.GetString("LanguageHelpText", resourceCulture);
            }
        }
        
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        public static string PreferredFileTypeDescription {
            get {
                return ResourceManager.GetString("PreferredFileTypeDescription", resourceCulture);
            }
        }
        
        public static string PreferredLanguageDescription {
            get {
                return ResourceManager.GetString("PreferredLanguageDescription", resourceCulture);
            }
        }
        
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        public static string PageSizeDescription {
            get {
                return ResourceManager.GetString("PageSizeDescription", resourceCulture);
            }
        }
        
        public static string TranslatorSelectionDescription {
            get {
                return ResourceManager.GetString("TranslatorSelectionDescription", resourceCulture);
            }
        }
        
        public static string TranslationProviderSettingsHeader {
            get {
                return ResourceManager.GetString("TranslationProviderSettingsHeader", resourceCulture);
            }
        }
        
        public static string TranslationProviderSettingsDescription {
            get {
                return ResourceManager.GetString("TranslationProviderSettingsDescription", resourceCulture);
            }
        }
        
        public static string TranslationProviderRoutingHint {
            get {
                return ResourceManager.GetString("TranslationProviderRoutingHint", resourceCulture);
            }
        }
        
        public static string TranslationProviderBaseUrlLabel {
            get {
                return ResourceManager.GetString("TranslationProviderBaseUrlLabel", resourceCulture);
            }
        }
        
        public static string TerminologySettingsHeader {
            get {
                return ResourceManager.GetString("TerminologySettingsHeader", resourceCulture);
            }
        }
        
        public static string TerminologySettingsDescription {
            get {
                return ResourceManager.GetString("TerminologySettingsDescription", resourceCulture);
            }
        }
        
        public static string TerminologyFilePath {
            get {
                return ResourceManager.GetString("TerminologyFilePath", resourceCulture);
            }
        }
        
        public static string StyleGuideSettingsHeader {
            get {
                return ResourceManager.GetString("StyleGuideSettingsHeader", resourceCulture);
            }
        }
        
        public static string StyleGuideSettingsDescription {
            get {
                return ResourceManager.GetString("StyleGuideSettingsDescription", resourceCulture);
            }
        }
        
        public static string StyleGuideFilePath {
            get {
                return ResourceManager.GetString("StyleGuideFilePath", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string PathInvalidCaption {
            get {
                return ResourceManager.GetString("PathInvalidCaption", resourceCulture);
            }
        }
        
        public static string PathInvalidMessage {
            get {
                return ResourceManager.GetString("PathInvalidMessage", resourceCulture);
            }
        }
        
        public static string PathInvalidIndicatorText {
            get {
                return ResourceManager.GetString("PathInvalidIndicatorText", resourceCulture);
            }
        }
        
        public static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        public static string PackageVersion {
            get {
                return ResourceManager.GetString("PackageVersion", resourceCulture);
            }
        }
        
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
