//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witcher3StringEditor.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutBtnLabel {
            get {
                return ResourceManager.GetString("AboutBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Record.
        /// </summary>
        public static string AddBtnLabel {
            get {
                return ResourceManager.GetString("AddBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Time:.
        /// </summary>
        public static string AppBuildTime {
            get {
                return ResourceManager.GetString("AppBuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string AppExitCaption {
            get {
                return ResourceManager.GetString("AppExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit? Any unsaved data will be lost..
        /// </summary>
        public static string AppExitMessage {
            get {
                return ResourceManager.GetString("AppExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Witcher 3 String Editor.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupBtnLabel {
            get {
                return ResourceManager.GetString("BackupBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Delete.
        /// </summary>
        public static string BackupDeleteCaption {
            get {
                return ResourceManager.GetString("BackupDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will permanently delete the file and cannot be undone. Are you sure you want to proceed?.
        /// </summary>
        public static string BackupDeleteMessage {
            get {
                return ResourceManager.GetString("BackupDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup File Not Found.
        /// </summary>
        public static string BackupFileNoFoundCaption {
            get {
                return ResourceManager.GetString("BackupFileNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup file does not exist. Would you like to proceed with deleting the record?.
        /// </summary>
        public static string BackupFileNoFoundMessage {
            get {
                return ResourceManager.GetString("BackupFileNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Path.
        /// </summary>
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Restore.
        /// </summary>
        public static string BackupRestoreCaption {
            get {
                return ResourceManager.GetString("BackupRestoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will overwrite the file and is not reversible. Are you sure you want to proceed?.
        /// </summary>
        public static string BackupRestoreMessage {
            get {
                return ResourceManager.GetString("BackupRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Time.
        /// </summary>
        public static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Translate.
        /// </summary>
        public static string BatchTranslateDialogTitle {
            get {
                return ResourceManager.GetString("BatchTranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtnContent {
            get {
                return ResourceManager.GetString("CancelBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseBtnContent {
            get {
                return ResourceManager.GetString("CloseBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBtnContent {
            get {
                return ResourceManager.GetString("DeleteBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Records.
        /// </summary>
        public static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the following record(s):.
        /// </summary>
        public static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop a Single File Here To Open.
        /// </summary>
        public static string DropHereTxt {
            get {
                return ResourceManager.GetString("DropHereTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        public static string EditBtnLabel {
            get {
                return ResourceManager.GetString("EditBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder Path.
        /// </summary>
        public static string EncoderSettingCardHeader {
            get {
                return ResourceManager.GetString("EncoderSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Index.
        /// </summary>
        public static string EndIndex {
            get {
                return ResourceManager.GetString("EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook.
        /// </summary>
        public static string FileFormatExcelWorkbook {
            get {
                return ResourceManager.GetString("FileFormatExcelWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Format.
        /// </summary>
        public static string FileFormatSupported {
            get {
                return ResourceManager.GetString("FileFormatSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File.
        /// </summary>
        public static string FileFormatTextFile {
            get {
                return ResourceManager.GetString("FileFormatTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Witcher3 String File.
        /// </summary>
        public static string FileFormatWitcher3StringsFile {
            get {
                return ResourceManager.GetString("FileFormatWitcher3StringsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened File Not Found.
        /// </summary>
        public static string FileOpenedNoFoundCaption {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opened file does not exist. Do you want to delete the associated record?.
        /// </summary>
        public static string FileOpenedNoFoundMessage {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-Run Setup Prompt.
        /// </summary>
        public static string FristRunCaption {
            get {
                return ResourceManager.GetString("FristRunCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Required) When running for the first time, please set the encoder path first.
        ///(Optional) Set the game executable path to launch the game directly in the software..
        /// </summary>
        public static string FristRunMessage {
            get {
                return ResourceManager.GetString("FristRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select witcher3.exe.
        /// </summary>
        public static string GameExePath {
            get {
                return ResourceManager.GetString("GameExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        public static string GameSettingCardHeader {
            get {
                return ResourceManager.GetString("GameSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Space.
        /// </summary>
        public static string IDSpace {
            get {
                return ResourceManager.GetString("IDSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range of the ID Space is a four-digit integer (from 0000 to 9999). When there is an error in detection, the program automatically indicates this by displaying the ID Space as negative one. Please note that the results are for reference only..
        /// </summary>
        public static string IdSpaceToolTip {
            get {
                return ResourceManager.GetString("IdSpaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore ID Space Check.
        /// </summary>
        public static string IgnoreIDSpaceCheck {
            get {
                return ResourceManager.GetString("IgnoreIDSpaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string IsOff {
            get {
                return ResourceManager.GetString("IsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string IsOn {
            get {
                return ResourceManager.GetString("IsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language for the application interface display.
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageHelpText {
            get {
                return ResourceManager.GetString("LanguageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogBtnLabel {
            get {
                return ResourceManager.GetString("LogBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogDialogTitle {
            get {
                return ResourceManager.GetString("LogDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software is already running.
        /// </summary>
        public static string MultipleInstanceCaption {
            get {
                return ResourceManager.GetString("MultipleInstanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple instances may cause data to be overwritten incorrectly. Only single-instance operation is supported. Do you want to bring up the already open window?.
        /// </summary>
        public static string MultipleInstanceMessage {
            get {
                return ResourceManager.GetString("MultipleInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextBtnContent {
            get {
                return ResourceManager.GetString("NextBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened Time.
        /// </summary>
        public static string OpenedTime {
            get {
                return ResourceManager.GetString("OpenedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFileBtnLabel {
            get {
                return ResourceManager.GetString("OpenFileBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Working Folder.
        /// </summary>
        public static string OpenWorkingFolderBtnLabel {
            get {
                return ResourceManager.GetString("OpenWorkingFolderBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operation Failed.
        /// </summary>
        public static string OperationFailureMessage {
            get {
                return ResourceManager.GetString("OperationFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Result.
        /// </summary>
        public static string OperationResultCaption {
            get {
                return ResourceManager.GetString("OperationResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Path.
        /// </summary>
        public static string OriginPath {
            get {
                return ResourceManager.GetString("OriginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS:.
        /// </summary>
        public static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the number of items displayed per page in the main interface data grid.
        /// </summary>
        public static string PageSizeDescription {
            get {
                return ResourceManager.GetString("PageSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path.
        /// </summary>
        public static string PathInvalidCaption {
            get {
                return ResourceManager.GetString("PathInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Invalid).
        /// </summary>
        public static string PathInvalidIndicatorText {
            get {
                return ResourceManager.GetString("PathInvalidIndicatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently set encoder path or game path is invalid. Please check your settings..
        /// </summary>
        public static string PathInvalidMessage {
            get {
                return ResourceManager.GetString("PathInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Game.
        /// </summary>
        public static string PlayBtnLabel {
            get {
                return ResourceManager.GetString("PlayBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred FileType.
        /// </summary>
        public static string PreferredFileType {
            get {
                return ResourceManager.GetString("PreferredFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the default file format for saving The Witcher 3 string files.
        /// </summary>
        public static string PreferredFileTypeDescription {
            get {
                return ResourceManager.GetString("PreferredFileTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target language for translation and the default language used when saving The Witcher 3 string files.
        /// </summary>
        public static string PreferredLanguageDescription {
            get {
                return ResourceManager.GetString("PreferredLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousBtnContent {
            get {
                return ResourceManager.GetString("PreviousBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentBtnLabel {
            get {
                return ResourceManager.GetString("RecentBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentDialogTitle {
            get {
                return ResourceManager.GetString("RecentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Record(s) Is Being Deleted.
        /// </summary>
        public static string RecordDeletingCaption {
            get {
                return ResourceManager.GetString("RecordDeletingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will permanently delete the selected record(s) and cannot be undone. Are you sure you want to proceed?.
        /// </summary>
        public static string RecordDeletingMessgae {
            get {
                return ResourceManager.GetString("RecordDeletingMessgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string ReOpenFileCaption {
            get {
                return ResourceManager.GetString("ReOpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening this file will result in the loss of any unsaved data. Do you want to continue?.
        /// </summary>
        public static string ReOpenFileMessage {
            get {
                return ResourceManager.GetString("ReOpenFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RestoreBtnContent {
            get {
                return ResourceManager.GetString("RestoreBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime:.
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtnContent {
            get {
                return ResourceManager.GetString("SaveBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failure.
        /// </summary>
        public static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Result.
        /// </summary>
        public static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select witcher3.exe.
        /// </summary>
        public static string SelectGameExe {
            get {
                return ResourceManager.GetString("SelectGameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select w3strings.exe.
        /// </summary>
        public static string SelectW3Strings {
            get {
                return ResourceManager.GetString("SelectW3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsBtnLabel {
            get {
                return ResourceManager.GetString("SettingsBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SrcTxt {
            get {
                return ResourceManager.GetString("SrcTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Index.
        /// </summary>
        public static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitBtnContent {
            get {
                return ResourceManager.GetString("SubmitBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Filetype.
        /// </summary>
        public static string TargetFiletype {
            get {
                return ResourceManager.GetString("TargetFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Language.
        /// </summary>
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string TranslateBtnContent {
            get {
                return ResourceManager.GetString("TranslateBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string TranslateBtnLabel {
            get {
                return ResourceManager.GetString("TranslateBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string TranslateDialogTitle {
            get {
                return ResourceManager.GetString("TranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Text Invalid.
        /// </summary>
        public static string TranslatedTextInvalidCaption {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translated text is invalid. Please review and correct it before saving..
        /// </summary>
        public static string TranslatedTextInvalidMessage {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Not Saved.
        /// </summary>
        public static string TranslatedTextNoSavedCaption {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation not saved. Save now?.
        /// </summary>
        public static string TranslatedTextNoSavedMessage {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Text.
        /// </summary>
        public static string TranslatedTxt {
            get {
                return ResourceManager.GetString("TranslatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Error.
        /// </summary>
        public static string TranslateErrorCaption {
            get {
                return ResourceManager.GetString("TranslateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twirling through Translation....
        /// </summary>
        public static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Translation Mode Confirmation.
        /// </summary>
        public static string TranslationModeSwitchCaption {
            get {
                return ResourceManager.GetString("TranslationModeSwitchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating. Switching translation modes will interrupt the process. Do you want to proceed with the switch?.
        /// </summary>
        public static string TranslationModeSwitchMessage {
            get {
                return ResourceManager.GetString("TranslationModeSwitchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translation already exists.
        /// </summary>
        public static string TranslationNotEmptyCaption {
            get {
                return ResourceManager.GetString("TranslationNotEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translation already exists. Do you want to overwrite the current result?.
        /// </summary>
        public static string TranslationNotEmptyMessage {
            get {
                return ResourceManager.GetString("TranslationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string TranslatorSelection {
            get {
                return ResourceManager.GetString("TranslatorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the translation service to use for translating text.
        /// </summary>
        public static string TranslatorSelectionDescription {
            get {
                return ResourceManager.GetString("TranslatorSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is Underway.
        /// </summary>
        public static string TranslatorTranslatingCaption {
            get {
                return ResourceManager.GetString("TranslatorTranslatingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translator is working hard on the translation. Do you really want to quit?.
        /// </summary>
        public static string TranslatorTranslatingMessage {
            get {
                return ResourceManager.GetString("TranslatorTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateBtnContent {
            get {
                return ResourceManager.GetString("UpdateBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface Settings.
        /// </summary>
        public static string UserInterfaceSettingsHeader {
            get {
                return ResourceManager.GetString("UserInterfaceSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select w3strings.exe.
        /// </summary>
        public static string W3StringsPath {
            get {
                return ResourceManager.GetString("W3StringsPath", resourceCulture);
            }
        }
    }
}
