//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witcher3StringEditor.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutBtnLabel {
            get {
                return ResourceManager.GetString("AboutBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Record 的本地化字符串。
        /// </summary>
        public static string AddBtnLabel {
            get {
                return ResourceManager.GetString("AddBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build Time: 的本地化字符串。
        /// </summary>
        public static string AppBuildTime {
            get {
                return ResourceManager.GetString("AppBuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string AppExitCaption {
            get {
                return ResourceManager.GetString("AppExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit? Any unsaved data will be lost. 的本地化字符串。
        /// </summary>
        public static string AppExitMessage {
            get {
                return ResourceManager.GetString("AppExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Witcher 3 String Editor 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        public static string BackupBtnLabel {
            get {
                return ResourceManager.GetString("BackupBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Delete 的本地化字符串。
        /// </summary>
        public static string BackupDeleteCaption {
            get {
                return ResourceManager.GetString("BackupDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will permanently delete the file and cannot be undone. Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        public static string BackupDeleteMessage {
            get {
                return ResourceManager.GetString("BackupDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        public static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup File Not Found 的本地化字符串。
        /// </summary>
        public static string BackupFileNoFoundCaption {
            get {
                return ResourceManager.GetString("BackupFileNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The backup file does not exist. Would you like to proceed with deleting the record? 的本地化字符串。
        /// </summary>
        public static string BackupFileNoFoundMessage {
            get {
                return ResourceManager.GetString("BackupFileNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Path 的本地化字符串。
        /// </summary>
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Restore 的本地化字符串。
        /// </summary>
        public static string BackupRestoreCaption {
            get {
                return ResourceManager.GetString("BackupRestoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will overwrite the file and is not reversible. Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        public static string BackupRestoreMessage {
            get {
                return ResourceManager.GetString("BackupRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Time 的本地化字符串。
        /// </summary>
        public static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Translate 的本地化字符串。
        /// </summary>
        public static string BatchTranslateDialogTitle {
            get {
                return ResourceManager.GetString("BatchTranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelBtnContent {
            get {
                return ResourceManager.GetString("CancelBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string CloseBtnContent {
            get {
                return ResourceManager.GetString("CloseBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string DeleteBtnContent {
            get {
                return ResourceManager.GetString("DeleteBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Records 的本地化字符串。
        /// </summary>
        public static string DeleteBtnLabel {
            get {
                return ResourceManager.GetString("DeleteBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are about to delete the following record(s): 的本地化字符串。
        /// </summary>
        public static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag and Drop a Single File Here To Open 的本地化字符串。
        /// </summary>
        public static string DropHereTxt {
            get {
                return ResourceManager.GetString("DropHereTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Record 的本地化字符串。
        /// </summary>
        public static string EditBtnLabel {
            get {
                return ResourceManager.GetString("EditBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoder Path 的本地化字符串。
        /// </summary>
        public static string EncoderSettingCardHeader {
            get {
                return ResourceManager.GetString("EncoderSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Index 的本地化字符串。
        /// </summary>
        public static string EndIndex {
            get {
                return ResourceManager.GetString("EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure 的本地化字符串。
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel Workbook 的本地化字符串。
        /// </summary>
        public static string FileFormatExcelWorkbook {
            get {
                return ResourceManager.GetString("FileFormatExcelWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Supported Format 的本地化字符串。
        /// </summary>
        public static string FileFormatSupported {
            get {
                return ResourceManager.GetString("FileFormatSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File 的本地化字符串。
        /// </summary>
        public static string FileFormatTextFile {
            get {
                return ResourceManager.GetString("FileFormatTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Witcher3 String File 的本地化字符串。
        /// </summary>
        public static string FileFormatWitcher3StringsFile {
            get {
                return ResourceManager.GetString("FileFormatWitcher3StringsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileName 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened File Not Found 的本地化字符串。
        /// </summary>
        public static string FileOpenedNoFoundCaption {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The opened file does not exist. Do you want to delete the associated record? 的本地化字符串。
        /// </summary>
        public static string FileOpenedNoFoundMessage {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First-Run Setup Prompt 的本地化字符串。
        /// </summary>
        public static string FristRunCaption {
            get {
                return ResourceManager.GetString("FristRunCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Required) When running for the first time, please set the encoder path first.
        ///(Optional) Set the game executable path to launch the game directly in the software. 的本地化字符串。
        /// </summary>
        public static string FristRunMessage {
            get {
                return ResourceManager.GetString("FristRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select witcher3.exe 的本地化字符串。
        /// </summary>
        public static string GameExePath {
            get {
                return ResourceManager.GetString("GameExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path 的本地化字符串。
        /// </summary>
        public static string GameSettingCardHeader {
            get {
                return ResourceManager.GetString("GameSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Settings 的本地化字符串。
        /// </summary>
        public static string GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash 的本地化字符串。
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID Space 的本地化字符串。
        /// </summary>
        public static string IDSpace {
            get {
                return ResourceManager.GetString("IDSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The range of the ID Space is a four-digit integer (from 0000 to 9999). When there is an error in detection, the program automatically indicates this by displaying the ID Space as negative one. Please note that the results are for reference only. 的本地化字符串。
        /// </summary>
        public static string IdSpaceToolTip {
            get {
                return ResourceManager.GetString("IdSpaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore ID Space Check 的本地化字符串。
        /// </summary>
        public static string IgnoreIDSpaceCheck {
            get {
                return ResourceManager.GetString("IgnoreIDSpaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string IsOff {
            get {
                return ResourceManager.GetString("IsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string IsOn {
            get {
                return ResourceManager.GetString("IsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the language for the application interface display 的本地化字符串。
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string LanguageHelpText {
            get {
                return ResourceManager.GetString("LanguageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string LogBtnLabel {
            get {
                return ResourceManager.GetString("LogBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string LogDialogTitle {
            get {
                return ResourceManager.GetString("LogDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Level 的本地化字符串。
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Message 的本地化字符串。
        /// </summary>
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Time 的本地化字符串。
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark 的本地化字符串。
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software is already running 的本地化字符串。
        /// </summary>
        public static string MultipleInstanceCaption {
            get {
                return ResourceManager.GetString("MultipleInstanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple instances may cause data to be overwritten incorrectly. Only single-instance operation is supported. Do you want to bring up the already open window? 的本地化字符串。
        /// </summary>
        public static string MultipleInstanceMessage {
            get {
                return ResourceManager.GetString("MultipleInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string NextBtnContent {
            get {
                return ResourceManager.GetString("NextBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened Time 的本地化字符串。
        /// </summary>
        public static string OpenedTime {
            get {
                return ResourceManager.GetString("OpenedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string OpenFileBtnLabel {
            get {
                return ResourceManager.GetString("OpenFileBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Working Folder 的本地化字符串。
        /// </summary>
        public static string OpenWorkingFolderBtnLabel {
            get {
                return ResourceManager.GetString("OpenWorkingFolderBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Operation Failed 的本地化字符串。
        /// </summary>
        public static string OperationFailureMessage {
            get {
                return ResourceManager.GetString("OperationFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Result 的本地化字符串。
        /// </summary>
        public static string OperationResultCaption {
            get {
                return ResourceManager.GetString("OperationResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Path 的本地化字符串。
        /// </summary>
        public static string OriginPath {
            get {
                return ResourceManager.GetString("OriginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS: 的本地化字符串。
        /// </summary>
        public static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Size 的本地化字符串。
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust the number of items displayed per page in the main interface data grid 的本地化字符串。
        /// </summary>
        public static string PageSizeDescription {
            get {
                return ResourceManager.GetString("PageSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Path 的本地化字符串。
        /// </summary>
        public static string PathInvalidCaption {
            get {
                return ResourceManager.GetString("PathInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The currently set encoder path or game path is invalid. Please check your settings. 的本地化字符串。
        /// </summary>
        public static string PathInvalidMessage {
            get {
                return ResourceManager.GetString("PathInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending 的本地化字符串。
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Game 的本地化字符串。
        /// </summary>
        public static string PlayBtnLabel {
            get {
                return ResourceManager.GetString("PlayBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred FileType 的本地化字符串。
        /// </summary>
        public static string PreferredFileType {
            get {
                return ResourceManager.GetString("PreferredFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the default file format for saving The Witcher 3 string files 的本地化字符串。
        /// </summary>
        public static string PreferredFileTypeDescription {
            get {
                return ResourceManager.GetString("PreferredFileTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Language 的本地化字符串。
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the target language for translation and the default language used when saving The Witcher 3 string files 的本地化字符串。
        /// </summary>
        public static string PreferredLanguageDescription {
            get {
                return ResourceManager.GetString("PreferredLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string PreviousBtnContent {
            get {
                return ResourceManager.GetString("PreviousBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 的本地化字符串。
        /// </summary>
        public static string RecentBtnLabel {
            get {
                return ResourceManager.GetString("RecentBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 的本地化字符串。
        /// </summary>
        public static string RecentDialogTitle {
            get {
                return ResourceManager.GetString("RecentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Record(s) Is Being Deleted 的本地化字符串。
        /// </summary>
        public static string RecordDeletingCaption {
            get {
                return ResourceManager.GetString("RecordDeletingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will permanently delete the selected record(s) and cannot be undone. Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        public static string RecordDeletingMessgae {
            get {
                return ResourceManager.GetString("RecordDeletingMessgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string ReOpenFileCaption {
            get {
                return ResourceManager.GetString("ReOpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening this file will result in the loss of any unsaved data. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string ReOpenFileMessage {
            get {
                return ResourceManager.GetString("ReOpenFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string RestoreBtnContent {
            get {
                return ResourceManager.GetString("RestoreBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime: 的本地化字符串。
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveBtnContent {
            get {
                return ResourceManager.GetString("SaveBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveBtnLabel {
            get {
                return ResourceManager.GetString("SaveBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Failure 的本地化字符串。
        /// </summary>
        public static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Result 的本地化字符串。
        /// </summary>
        public static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Success 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select witcher3.exe 的本地化字符串。
        /// </summary>
        public static string SelectGameExe {
            get {
                return ResourceManager.GetString("SelectGameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select w3strings.exe 的本地化字符串。
        /// </summary>
        public static string SelectW3Strings {
            get {
                return ResourceManager.GetString("SelectW3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsBtnLabel {
            get {
                return ResourceManager.GetString("SettingsBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string SrcTxt {
            get {
                return ResourceManager.GetString("SrcTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Index 的本地化字符串。
        /// </summary>
        public static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string SubmitBtnContent {
            get {
                return ResourceManager.GetString("SubmitBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Filetype 的本地化字符串。
        /// </summary>
        public static string TargetFiletype {
            get {
                return ResourceManager.GetString("TargetFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Language 的本地化字符串。
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Language 的本地化字符串。
        /// </summary>
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        public static string TranslateBtnContent {
            get {
                return ResourceManager.GetString("TranslateBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        public static string TranslateBtnLabel {
            get {
                return ResourceManager.GetString("TranslateBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        public static string TranslateDialogTitle {
            get {
                return ResourceManager.GetString("TranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translated Text Invalid 的本地化字符串。
        /// </summary>
        public static string TranslatedTextInvalidCaption {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translated text is invalid. Please review and correct it before saving. 的本地化字符串。
        /// </summary>
        public static string TranslatedTextInvalidMessage {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Not Saved 的本地化字符串。
        /// </summary>
        public static string TranslatedTextNoSavedCaption {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation not saved. Save now? 的本地化字符串。
        /// </summary>
        public static string TranslatedTextNoSavedMessage {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translated Text 的本地化字符串。
        /// </summary>
        public static string TranslatedTxt {
            get {
                return ResourceManager.GetString("TranslatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate Error 的本地化字符串。
        /// </summary>
        public static string TranslateErrorCaption {
            get {
                return ResourceManager.GetString("TranslateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twirling through Translation... 的本地化字符串。
        /// </summary>
        public static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Translation Mode Confirmation 的本地化字符串。
        /// </summary>
        public static string TranslationModeSwitchCaption {
            get {
                return ResourceManager.GetString("TranslationModeSwitchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translating. Switching translation modes will interrupt the process. Do you want to proceed with the switch? 的本地化字符串。
        /// </summary>
        public static string TranslationModeSwitchMessage {
            get {
                return ResourceManager.GetString("TranslationModeSwitchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translation already exists 的本地化字符串。
        /// </summary>
        public static string TranslationNotEmptyCaption {
            get {
                return ResourceManager.GetString("TranslationNotEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translation already exists. Do you want to overwrite the current result? 的本地化字符串。
        /// </summary>
        public static string TranslationNotEmptyMessage {
            get {
                return ResourceManager.GetString("TranslationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translator 的本地化字符串。
        /// </summary>
        public static string TranslatorSelection {
            get {
                return ResourceManager.GetString("TranslatorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the translation service to use for translating text 的本地化字符串。
        /// </summary>
        public static string TranslatorSelectionDescription {
            get {
                return ResourceManager.GetString("TranslatorSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation is Underway 的本地化字符串。
        /// </summary>
        public static string TranslatorTranslatingCaption {
            get {
                return ResourceManager.GetString("TranslatorTranslatingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translator is working hard on the translation. Do you really want to quit? 的本地化字符串。
        /// </summary>
        public static string TranslatorTranslatingMessage {
            get {
                return ResourceManager.GetString("TranslatorTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Available 的本地化字符串。
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string UpdateBtnContent {
            get {
                return ResourceManager.GetString("UpdateBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Interface Settings 的本地化字符串。
        /// </summary>
        public static string UserInterfaceSettingsHeader {
            get {
                return ResourceManager.GetString("UserInterfaceSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select w3strings.exe 的本地化字符串。
        /// </summary>
        public static string W3StringsPath {
            get {
                return ResourceManager.GetString("W3StringsPath", resourceCulture);
            }
        }
    }
}
