//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Dialogs.Locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witcher3StringEditor.Dialogs.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AI Translator(Experimental) 的本地化字符串。
        /// </summary>
        internal static string AiTranslatorSettingsHeader {
            get {
                return ResourceManager.GetString("AiTranslatorSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once the AI Translator is enabled, the system will automatically replace the existing Microsoft Translator as the default translation engine. 的本地化字符串。
        /// </summary>
        internal static string AiTranslatorSwitchDescription {
            get {
                return ResourceManager.GetString("AiTranslatorSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AI Translator 的本地化字符串。
        /// </summary>
        internal static string AiTranslatorSwitchHeader {
            get {
                return ResourceManager.GetString("AiTranslatorSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build Time: 的本地化字符串。
        /// </summary>
        internal static string AppBuildTime {
            get {
                return ResourceManager.GetString("AppBuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Delete 的本地化字符串。
        /// </summary>
        internal static string BackupDeleteCaption {
            get {
                return ResourceManager.GetString("BackupDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will permanently delete the file and cannot be undone. Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        internal static string BackupDeleteMessage {
            get {
                return ResourceManager.GetString("BackupDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        internal static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup File Not Found 的本地化字符串。
        /// </summary>
        internal static string BackupFileNoFoundCaption {
            get {
                return ResourceManager.GetString("BackupFileNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The backup file does not exist. Would you like to proceed with deleting the record? 的本地化字符串。
        /// </summary>
        internal static string BackupFileNoFoundMessage {
            get {
                return ResourceManager.GetString("BackupFileNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Path 的本地化字符串。
        /// </summary>
        internal static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Restore 的本地化字符串。
        /// </summary>
        internal static string BackupRestoreCaption {
            get {
                return ResourceManager.GetString("BackupRestoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will overwrite the file and is not reversible. Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        internal static string BackupRestoreMessage {
            get {
                return ResourceManager.GetString("BackupRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Time 的本地化字符串。
        /// </summary>
        internal static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Translate 的本地化字符串。
        /// </summary>
        internal static string BatchTranslateDialogTitle {
            get {
                return ResourceManager.GetString("BatchTranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelBtnContent {
            get {
                return ResourceManager.GetString("CancelBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear the Knowledge Base 的本地化字符串。
        /// </summary>
        internal static string ClearKnowledgeBtnContent {
            get {
                return ResourceManager.GetString("ClearKnowledgeBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseBtnContent {
            get {
                return ResourceManager.GetString("CloseBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls the number of historical messages considered by the model when generating replies. Increasing this value can improve reply accuracy but may decrease speed and increase costs. Setting it to 0 disables this option, meaning the model will not consider any historical messages. 的本地化字符串。
        /// </summary>
        internal static string ContextLengthSettingDescription {
            get {
                return ResourceManager.GetString("ContextLengthSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Context Length 的本地化字符串。
        /// </summary>
        internal static string ContextLengthSettingHeader {
            get {
                return ResourceManager.GetString("ContextLengthSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteBtnContent {
            get {
                return ResourceManager.GetString("DeleteBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are about to delete the following record(s): 的本地化字符串。
        /// </summary>
        internal static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Knowledge 的本地化字符串。
        /// </summary>
        internal static string DelKnowledgeBtnContent {
            get {
                return ResourceManager.GetString("DelKnowledgeBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoder Path 的本地化字符串。
        /// </summary>
        internal static string EncoderSettingCardHeader {
            get {
                return ResourceManager.GetString("EncoderSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Index 的本地化字符串。
        /// </summary>
        internal static string EndIndex {
            get {
                return ResourceManager.GetString("EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileName 的本地化字符串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select witcher3.exe 的本地化字符串。
        /// </summary>
        internal static string GameExePath {
            get {
                return ResourceManager.GetString("GameExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path 的本地化字符串。
        /// </summary>
        internal static string GameSettingCardHeader {
            get {
                return ResourceManager.GetString("GameSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Settings 的本地化字符串。
        /// </summary>
        internal static string GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash 的本地化字符串。
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID Space 的本地化字符串。
        /// </summary>
        internal static string IDSpace {
            get {
                return ResourceManager.GetString("IDSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The range of the ID Space is a four-digit integer (from 0000 to 9999). When there is an error in detection, the program automatically indicates this by displaying the ID Space as negative one. Please note that the results are for reference only. 的本地化字符串。
        /// </summary>
        internal static string IdSpaceToolTip {
            get {
                return ResourceManager.GetString("IdSpaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore ID Space Check     的本地化字符串。
        /// </summary>
        internal static string IgnoreIDSpaceCheck {
            get {
                return ResourceManager.GetString("IgnoreIDSpaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Knowledge 的本地化字符串。
        /// </summary>
        internal static string ImportKnowledgeBtnContent {
            get {
                return ResourceManager.GetString("ImportKnowledgeBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incomplete AI Translation Settings 的本地化字符串。
        /// </summary>
        internal static string IncompleteAiTranslationSettingsCaption {
            get {
                return ResourceManager.GetString("IncompleteAiTranslationSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AI translation is activated but settings are incomplete. Exiting now will disable the feature until re-configured.
        ///- Click &quot;Yes&quot; to exit and disable AI translation.
        ///- Click &quot;No&quot; to return to settings and complete configuration. 的本地化字符串。
        /// </summary>
        internal static string IncompleteAiTranslationSettingsMessage {
            get {
                return ResourceManager.GetString("IncompleteAiTranslationSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization Incomplete 的本地化字符串。
        /// </summary>
        internal static string InitializationIncompleteCaption {
            get {
                return ResourceManager.GetString("InitializationIncompleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have not completed the initialization.
        ///- Click &quot;Yes&quot; to exit the program.
        ///- Click &quot;No&quot; to continue with the initialization. 的本地化字符串。
        /// </summary>
        internal static string InitializationIncompleteMessage {
            get {
                return ResourceManager.GetString("InitializationIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please note the token consumption when using the AI translator 的本地化字符串。
        /// </summary>
        internal static string IsAiTranslatorHelpTxt {
            get {
                return ResourceManager.GetString("IsAiTranslatorHelpTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string IsOff {
            get {
                return ResourceManager.GetString("IsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string IsOn {
            get {
                return ResourceManager.GetString("IsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Players need to add content to this knowledge base themselves to provide references for AI translators. 的本地化字符串。
        /// </summary>
        internal static string KnowledgeBaseDescription {
            get {
                return ResourceManager.GetString("KnowledgeBaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knowledge Base 的本地化字符串。
        /// </summary>
        internal static string KnowledgeBaseSwitchHeader {
            get {
                return ResourceManager.GetString("KnowledgeBaseSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Knowledge Base  的本地化字符串。
        /// </summary>
        internal static string KnowledgeDialogTitle {
            get {
                return ResourceManager.GetString("KnowledgeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string LogDialogTitle {
            get {
                return ResourceManager.GetString("LogDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Level 的本地化字符串。
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Message 的本地化字符串。
        /// </summary>
        internal static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Time 的本地化字符串。
        /// </summary>
        internal static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark 的本地化字符串。
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access Key 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsApiKeyDescription {
            get {
                return ResourceManager.GetString("ModelSettingsApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API Key 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsApiKeyHeader {
            get {
                return ResourceManager.GetString("ModelSettingsApiKeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Generation Model with Support for OpenAI API Specifications 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsDescription {
            get {
                return ResourceManager.GetString("ModelSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API URL 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsEndpointDescription {
            get {
                return ResourceManager.GetString("ModelSettingsEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Endpoint 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsEndpointHeader {
            get {
                return ResourceManager.GetString("ModelSettingsEndpointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Settings 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsHeader {
            get {
                return ResourceManager.GetString("ModelSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model identifier 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsModelIDDescription {
            get {
                return ResourceManager.GetString("ModelSettingsModelIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model ID 的本地化字符串。
        /// </summary>
        internal static string ModelSettingsModelIDHeader {
            get {
                return ResourceManager.GetString("ModelSettingsModelIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string NextBtnContent {
            get {
                return ResourceManager.GetString("NextBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened Time 的本地化字符串。
        /// </summary>
        internal static string OpenedTime {
            get {
                return ResourceManager.GetString("OpenedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Operation Failed 的本地化字符串。
        /// </summary>
        internal static string OperationFailureMessage {
            get {
                return ResourceManager.GetString("OperationFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Result 的本地化字符串。
        /// </summary>
        internal static string OperationResultCaption {
            get {
                return ResourceManager.GetString("OperationResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orgin Path 的本地化字符串。
        /// </summary>
        internal static string OrginPath {
            get {
                return ResourceManager.GetString("OrginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS: 的本地化字符串。
        /// </summary>
        internal static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending 的本地化字符串。
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred FileType 的本地化字符串。
        /// </summary>
        internal static string PreferredFileType {
            get {
                return ResourceManager.GetString("PreferredFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Language 的本地化字符串。
        /// </summary>
        internal static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        internal static string PreviousBtnContent {
            get {
                return ResourceManager.GetString("PreviousBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompts are input texts or instructions given to an AI model to generate specific responses. They can range from simple phrases to complex sentences, guiding the model on what kind of output is expected. 的本地化字符串。
        /// </summary>
        internal static string PromptsSettingsDescription {
            get {
                return ResourceManager.GetString("PromptsSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompts 的本地化字符串。
        /// </summary>
        internal static string PromptsSettingsHeader {
            get {
                return ResourceManager.GetString("PromptsSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 的本地化字符串。
        /// </summary>
        internal static string RecentDialogTitle {
            get {
                return ResourceManager.GetString("RecentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Record(s) Is Being Deleted 的本地化字符串。
        /// </summary>
        internal static string RecordDeletingCaption {
            get {
                return ResourceManager.GetString("RecordDeletingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will permanently delete the selected record(s) and cannot be undone. Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        internal static string RecordDeletingMessgae {
            get {
                return ResourceManager.GetString("RecordDeletingMessgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        internal static string RestoreBtnContent {
            get {
                return ResourceManager.GetString("RestoreBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime: 的本地化字符串。
        /// </summary>
        internal static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveBtnContent {
            get {
                return ResourceManager.GetString("SaveBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Failure 的本地化字符串。
        /// </summary>
        internal static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Result 的本地化字符串。
        /// </summary>
        internal static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Success 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select witcher3.exe 的本地化字符串。
        /// </summary>
        internal static string SelectGameExe {
            get {
                return ResourceManager.GetString("SelectGameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select w3strings.exe 的本地化字符串。
        /// </summary>
        internal static string SelectW3Strings {
            get {
                return ResourceManager.GetString("SelectW3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string SrcTxt {
            get {
                return ResourceManager.GetString("SrcTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Index 的本地化字符串。
        /// </summary>
        internal static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string SubmitBtnContent {
            get {
                return ResourceManager.GetString("SubmitBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Filetype 的本地化字符串。
        /// </summary>
        internal static string TargetFiletype {
            get {
                return ResourceManager.GetString("TargetFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Language 的本地化字符串。
        /// </summary>
        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls the randomness and creativity of the generated text. Lower values make the output more deterministic and focused on the highest probability options, while higher values increase diversity but may reduce coherence. Recommended range: 0 to 2. Setting the value to 0 disables this option. 的本地化字符串。
        /// </summary>
        internal static string TemperatureSettingDescription {
            get {
                return ResourceManager.GetString("TemperatureSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Randomness 的本地化字符串。
        /// </summary>
        internal static string TemperatureSettingHeader {
            get {
                return ResourceManager.GetString("TemperatureSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Language 的本地化字符串。
        /// </summary>
        internal static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamically adjusts the sampling process by selecting from the smallest set of most probable tokens based on cumulative probability. This method increases output diversity while maintaining quality. Recommended range: 0 to 1. Setting the value to 0 disables this option. 的本地化字符串。
        /// </summary>
        internal static string TopPSettingDescription {
            get {
                return ResourceManager.GetString("TopPSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cumulative Probability 的本地化字符串。
        /// </summary>
        internal static string TopPSettingHeader {
            get {
                return ResourceManager.GetString("TopPSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        internal static string TranslateBtnContent {
            get {
                return ResourceManager.GetString("TranslateBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Too Long 的本地化字符串。
        /// </summary>
        internal static string TranslateCharactersNumberExceedLimitCaption {
            get {
                return ResourceManager.GetString("TranslateCharactersNumberExceedLimitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The text you&apos;ve entered exceeds the maximum allowed length of 1,000 characters for translation. 的本地化字符串。
        /// </summary>
        internal static string TranslateCharactersNumberExceedLimitMessage {
            get {
                return ResourceManager.GetString("TranslateCharactersNumberExceedLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translator allows a maximum of 1,000 characters 的本地化字符串。
        /// </summary>
        internal static string TranslateCharactersNumberLimit {
            get {
                return ResourceManager.GetString("TranslateCharactersNumberLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        internal static string TranslateDialogTitle {
            get {
                return ResourceManager.GetString("TranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translated Text Invalid 的本地化字符串。
        /// </summary>
        internal static string TranslatedTextInvalidCaption {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translated text is invalid. Please review and correct it before saving. 的本地化字符串。
        /// </summary>
        internal static string TranslatedTextInvalidMessage {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Not Save 的本地化字符串。
        /// </summary>
        internal static string TranslatedTextNoSavedCaption {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation not saved. Save now? 的本地化字符串。
        /// </summary>
        internal static string TranslatedTextNoSavedMessage {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translated Text 的本地化字符串。
        /// </summary>
        internal static string TranslatedTxt {
            get {
                return ResourceManager.GetString("TranslatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate Error 的本地化字符串。
        /// </summary>
        internal static string TranslateErrorCaption {
            get {
                return ResourceManager.GetString("TranslateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twirling through Translation... 的本地化字符串。
        /// </summary>
        internal static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Translation Mode Confirmation 的本地化字符串。
        /// </summary>
        internal static string TranslationModeSwitchCaption {
            get {
                return ResourceManager.GetString("TranslationModeSwitchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translating. Switching translation modes will interrupt the process. Do you want to proceed with the switch? 的本地化字符串。
        /// </summary>
        internal static string TranslationModeSwitchMessage {
            get {
                return ResourceManager.GetString("TranslationModeSwitchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translation already exists 的本地化字符串。
        /// </summary>
        internal static string TranslationNotEmptyCaption {
            get {
                return ResourceManager.GetString("TranslationNotEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translation already exists. Do you want to overwrite the current result? 的本地化字符串。
        /// </summary>
        internal static string TranslationNotEmptyMessage {
            get {
                return ResourceManager.GetString("TranslationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation is Underway 的本地化字符串。
        /// </summary>
        internal static string TranslatorTranslatingCaption {
            get {
                return ResourceManager.GetString("TranslatorTranslatingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translator is working hard on the translation. Do you really want to quit? 的本地化字符串。
        /// </summary>
        internal static string TranslatorTranslatingMessage {
            get {
                return ResourceManager.GetString("TranslatorTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select w3strings.exe 的本地化字符串。
        /// </summary>
        internal static string W3StringsPath {
            get {
                return ResourceManager.GetString("W3StringsPath", resourceCulture);
            }
        }
    }
}
