//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witcher3StringEditor.Dialogs.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Witcher3StringEditor.Dialogs.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Translator(Experimental).
        /// </summary>
        internal static string AiTranslatorSettingsHeader {
            get {
                return ResourceManager.GetString("AiTranslatorSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the AI Translator is enabled, the system will automatically replace the existing Microsoft Translator as the default translation engine.
        /// </summary>
        internal static string AiTranslatorSwitchDescription {
            get {
                return ResourceManager.GetString("AiTranslatorSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Translator.
        /// </summary>
        internal static string AiTranslatorSwitchHeader {
            get {
                return ResourceManager.GetString("AiTranslatorSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Time:.
        /// </summary>
        internal static string AppBuildTime {
            get {
                return ResourceManager.GetString("AppBuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Delete.
        /// </summary>
        internal static string BackupDeleteCaption {
            get {
                return ResourceManager.GetString("BackupDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will permanently delete the file and cannot be undone. Are you sure you want to proceed?.
        /// </summary>
        internal static string BackupDeleteMessage {
            get {
                return ResourceManager.GetString("BackupDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupDialogTitle {
            get {
                return ResourceManager.GetString("BackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup File Not Found.
        /// </summary>
        internal static string BackupFileNoFoundCaption {
            get {
                return ResourceManager.GetString("BackupFileNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup file does not exist. Would you like to proceed with deleting the record?.
        /// </summary>
        internal static string BackupFileNoFoundMessage {
            get {
                return ResourceManager.GetString("BackupFileNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Path.
        /// </summary>
        internal static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Restore.
        /// </summary>
        internal static string BackupRestoreCaption {
            get {
                return ResourceManager.GetString("BackupRestoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will overwrite the file and is not reversible. Are you sure you want to proceed?.
        /// </summary>
        internal static string BackupRestoreMessage {
            get {
                return ResourceManager.GetString("BackupRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Time.
        /// </summary>
        internal static string BackupTime {
            get {
                return ResourceManager.GetString("BackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Translate.
        /// </summary>
        internal static string BatchTranslateDialogTitle {
            get {
                return ResourceManager.GetString("BatchTranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtnContent {
            get {
                return ResourceManager.GetString("CancelBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Invalid.
        /// </summary>
        internal static string CheckSettingsCaption {
            get {
                return ResourceManager.GetString("CheckSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization has not been completed. Do you wish to exit without completing it? Click YES to exit, or NO to continue and complete the initialization..
        /// </summary>
        internal static string CheckSettingsMessage {
            get {
                return ResourceManager.GetString("CheckSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseBtnContent {
            get {
                return ResourceManager.GetString("CloseBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtnContent {
            get {
                return ResourceManager.GetString("DeleteBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the following record(s):.
        /// </summary>
        internal static string DeleteDialogMessage {
            get {
                return ResourceManager.GetString("DeleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating.
        /// </summary>
        internal static string DialogClosingWhenTranslatingCaption {
            get {
                return ResourceManager.GetString("DialogClosingWhenTranslatingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is currently in progress. Closing this window will stop the translation. Do you want to continue translating?.
        /// </summary>
        internal static string DialogClosingWhenTranslatingMessage {
            get {
                return ResourceManager.GetString("DialogClosingWhenTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder Path.
        /// </summary>
        internal static string EncoderSettingCardHeader {
            get {
                return ResourceManager.GetString("EncoderSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Index.
        /// </summary>
        internal static string EndIndex {
            get {
                return ResourceManager.GetString("EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select witcher3.exe.
        /// </summary>
        internal static string GameExePath {
            get {
                return ResourceManager.GetString("GameExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        internal static string GameSettingCardHeader {
            get {
                return ResourceManager.GetString("GameSettingCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Space.
        /// </summary>
        internal static string IDSpace {
            get {
                return ResourceManager.GetString("IDSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range of the ID Space is a four-digit integer (from 0000 to 9999). When there is an error in detection, the program automatically indicates this by displaying the ID Space as negative one. Please note that the results are for reference only..
        /// </summary>
        internal static string IdSpaceToolTip {
            get {
                return ResourceManager.GetString("IdSpaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore ID Space Check    .
        /// </summary>
        internal static string IgnoreIDSpaceCheck {
            get {
                return ResourceManager.GetString("IgnoreIDSpaceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string IsOff {
            get {
                return ResourceManager.GetString("IsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string IsOn {
            get {
                return ResourceManager.GetString("IsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogDialogTitle {
            get {
                return ResourceManager.GetString("LogDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        internal static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        internal static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security token.
        /// </summary>
        internal static string ModelSettingsApiKeyDescription {
            get {
                return ResourceManager.GetString("ModelSettingsApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string ModelSettingsApiKeyHeader {
            get {
                return ResourceManager.GetString("ModelSettingsApiKeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Generation Model with Support for OpenAI API Specifications.
        /// </summary>
        internal static string ModelSettingsDescription {
            get {
                return ResourceManager.GetString("ModelSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API URL.
        /// </summary>
        internal static string ModelSettingsEndpointDescription {
            get {
                return ResourceManager.GetString("ModelSettingsEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        internal static string ModelSettingsEndpointHeader {
            get {
                return ResourceManager.GetString("ModelSettingsEndpointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Settings.
        /// </summary>
        internal static string ModelSettingsHeader {
            get {
                return ResourceManager.GetString("ModelSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model identifier.
        /// </summary>
        internal static string ModelSettingsModelIDDescription {
            get {
                return ResourceManager.GetString("ModelSettingsModelIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ID.
        /// </summary>
        internal static string ModelSettingsModelIDHeader {
            get {
                return ResourceManager.GetString("ModelSettingsModelIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextBtnContent {
            get {
                return ResourceManager.GetString("NextBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened Time.
        /// </summary>
        internal static string OpenedTime {
            get {
                return ResourceManager.GetString("OpenedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operation Failed.
        /// </summary>
        internal static string OperationFailureMessage {
            get {
                return ResourceManager.GetString("OperationFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Result.
        /// </summary>
        internal static string OperationResultCaption {
            get {
                return ResourceManager.GetString("OperationResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgin Path.
        /// </summary>
        internal static string OrginPath {
            get {
                return ResourceManager.GetString("OrginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS:.
        /// </summary>
        internal static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred FileType.
        /// </summary>
        internal static string PreferredFileType {
            get {
                return ResourceManager.GetString("PreferredFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        internal static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousBtnContent {
            get {
                return ResourceManager.GetString("PreviousBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompts are input texts or instructions given to an AI model to generate specific responses. They can range from simple phrases to complex sentences, guiding the model on what kind of output is expected.
        /// </summary>
        internal static string PromptsSettingsDescription {
            get {
                return ResourceManager.GetString("PromptsSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompts.
        /// </summary>
        internal static string PromptsSettingsHeader {
            get {
                return ResourceManager.GetString("PromptsSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string RecentDialogTitle {
            get {
                return ResourceManager.GetString("RecentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Record(s) Is Being Deleted.
        /// </summary>
        internal static string RecordDeletingCaption {
            get {
                return ResourceManager.GetString("RecordDeletingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will permanently delete the selected record(s) and cannot be undone. Are you sure you want to proceed?.
        /// </summary>
        internal static string RecordDeletingMessgae {
            get {
                return ResourceManager.GetString("RecordDeletingMessgae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string RestoreBtnContent {
            get {
                return ResourceManager.GetString("RestoreBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime:.
        /// </summary>
        internal static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtnContent {
            get {
                return ResourceManager.GetString("SaveBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failure.
        /// </summary>
        internal static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Result.
        /// </summary>
        internal static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select witcher3.exe.
        /// </summary>
        internal static string SelectGameExe {
            get {
                return ResourceManager.GetString("SelectGameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select w3strings.exe.
        /// </summary>
        internal static string SelectW3Strings {
            get {
                return ResourceManager.GetString("SelectW3Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string SrcTxt {
            get {
                return ResourceManager.GetString("SrcTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Index.
        /// </summary>
        internal static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitBtnContent {
            get {
                return ResourceManager.GetString("SubmitBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Filetype.
        /// </summary>
        internal static string TargetFiletype {
            get {
                return ResourceManager.GetString("TargetFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Language.
        /// </summary>
        internal static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string TranslateBtnContent {
            get {
                return ResourceManager.GetString("TranslateBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Too Long.
        /// </summary>
        internal static string TranslateCharactersNumberExceedLimitCaption {
            get {
                return ResourceManager.GetString("TranslateCharactersNumberExceedLimitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text you&apos;ve entered exceeds the maximum allowed length of 1,000 characters for translation..
        /// </summary>
        internal static string TranslateCharactersNumberExceedLimitMessage {
            get {
                return ResourceManager.GetString("TranslateCharactersNumberExceedLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translator allows a maximum of 1,000 characters.
        /// </summary>
        internal static string TranslateCharactersNumberLimit {
            get {
                return ResourceManager.GetString("TranslateCharactersNumberLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string TranslateDialogTitle {
            get {
                return ResourceManager.GetString("TranslateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Text Invalid.
        /// </summary>
        internal static string TranslatedTextInvalidCaption {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translated text is invalid. Please review and correct it before saving..
        /// </summary>
        internal static string TranslatedTextInvalidMessage {
            get {
                return ResourceManager.GetString("TranslatedTextInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Not Save.
        /// </summary>
        internal static string TranslatedTextNoSavedCaption {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation not saved. Save now?.
        /// </summary>
        internal static string TranslatedTextNoSavedMessage {
            get {
                return ResourceManager.GetString("TranslatedTextNoSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Text.
        /// </summary>
        internal static string TranslatedTxt {
            get {
                return ResourceManager.GetString("TranslatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Error.
        /// </summary>
        internal static string TranslateErrorCaption {
            get {
                return ResourceManager.GetString("TranslateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is Underway.
        /// </summary>
        internal static string TranslatorTranslatingCaption {
            get {
                return ResourceManager.GetString("TranslatorTranslatingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translator is working hard on the translation. Do you really want to quit?.
        /// </summary>
        internal static string TranslatorTranslatingMessage {
            get {
                return ResourceManager.GetString("TranslatorTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select w3strings.exe.
        /// </summary>
        internal static string W3StringsPath {
            get {
                return ResourceManager.GetString("W3StringsPath", resourceCulture);
            }
        }
    }
}
